title: [Cal McLean - on GitHub](//calmcl1.github.io)!
description: [I'm Cal](//calmcl1.github.io) - a vision mixer with too much time.
google_analytics: 
show_downloads: false
theme: jekyll-theme-minimal

gems:
  - jekyll-mentions
